### ISSUE TITLE
Use an output log file instead of the std out print callback

### ISSUE THREAD

**Issue by raquel-ucl** [DCPROGS/HJCFIT#104]
Remis says it's important to be able to see the output as the jobs run, but the printout callback takes half the time of the execution. We have disabled it for the performance tests, but we should consider using a log file and check how much that slows things down.

**Comment by jenshnielsen** [comment]
We figured out that the main issue is that the script calls the likelihood calculation for every iteration even when only printing the callback for every 10 iterations. Moving the calculation into the if statement fixes this
