### ISSUE TITLE
Fix tests currently running on Legion

### ISSUE THREAD

**Issue by raquel-ucl** [DCPROGS/HJCFIT#68]
See http://development.rc.ucl.ac.uk/jenkins/view/dcprogs/job/dcprogs-main/430/console

**Comment by jenshnielsen** [comment]
Main thinks to do afaik 

- [ ] swig is not build for Intel
- [ ] I have manually installed the python dependencies with `pip install --user` as ccsprsd on Legion. We should probably do something better.
- [ ] On OSX the gcc version is hardcoded and have changes due to a brew upgrade

**Comment by raquel-ucl** [comment]
Test are working now, @jenshnielsen do we need to go through those three tasks you mentioned as well minus swig for Intel?

**Comment by jenshnielsen** [comment]
I fixed number 3. We can thing about improving number 2 but it's not urgent.

**Comment by jenshnielsen** [comment]
Actually it would be good to also add tests
